on: push
name: Run phpunit testsuite
jobs:
  phpunit:
    runs-on: ubuntu-latest
    container:
      # image: kirschbaumdevelopment/laravel-test-runner
      image: mattiasgeniar/php73

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_USER: root
          MYSQL_PASSWORD: root
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test
        ports:
        - 33306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
    - name: Verify MySQL connection from host
      run: |
        sudo apt-get install -y mysql-client
        mysql --host 127.0.0.1 --port ${{ job.services.mysql.ports['3306'] }} -uroot -ppassword -e "SHOW DATABASES"

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    # - name: Setup Database
    #   run: |
    #     service mysql start
    #     mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

    - name: Test MySQL connection
      run: |
        mysql -u root -proot -e "show tables from test;"

    - name: Install composer dependencies
      run: |
        composer install --no-scripts

    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate

    - name: Run Testsuite
      run: vendor/bin/phpunit tests/
