on: push
name: Run phpunit testsuite
jobs:
  phpunit:
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: password
          MYSQL_DATABASE: test
        ports:
          - 8888:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    runs-on: ubuntu-latest
    # container:
      # image: kirschbaumdevelopment/laravel-test-runner
      # image: mattiasgeniar/php73

    steps:
    - name: Test MySQL connection
      run: |
        mysql -h 127.0.0.1 --port 8888 -u root -ppassword -e "CREATE DATABASE IF NOT EXISTS test;"

    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    # - name: Setup Database
    #   run: |
    #     service mysql start
    #     mysql -e 'CREATE DATABASE IF NOT EXISTS test;'

    - name: Install composer dependencies
      run: |
        composer install --no-scripts

    - name: Prepare Laravel Application
      run: |
        cp .env.ci .env
        php artisan key:generate

    - name: Run Testsuite
      run: vendor/bin/phpunit tests/
